version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ actions"
    labels:
      - dependencies
      - actions

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ gradle"
    labels:
      - dependencies
      - gradle

  - package-ecosystem: "gradle"
    directory: "/build-logic"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ gradle (build-logic)"
    labels:
      - dependencies
      - build-logic

  - package-ecosystem: "bundler"
    directories:
      #      - "/sites/toad"
      - "/sites/tom"
    #      - "/sites/yoshi"
    #      - "/sites/jerry"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ bundler"
    labels:
      - dependencies
      - jekyll
