constitution:
  - changed-files:
      - any-glob-to-any-file:
        - '*'
        - build-logic/**
        - .github/**

site:
  - changed-files:
      - any-glob-to-any-file: sites/**

assets:
  - changed-files:
      - any-glob-to-any-file: assets/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
