constitution:
  - changed-files:
      - any-glob-to-any-file:
        - '*'
        - build-logic/**

action:
  - changed-files:
      - any-glob-to-any-file:
        - .github/actions/**
        - .github/workflows/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
        - gradle/**
        - '*.gradle.kts'
        - gradle.properties
        - .sdkmanrc

maintenance:
  - changed-files:
      - any-glob-to-any-file:
        - src/main/sh/**
        - .github/labeler.yml
        - .gitignore
