#!/usr/bin/env zsh
#
### Script: catalog
# A catalog of available shell actions and functions in the Mimis actions framework.
# There are low-level functions and functional action functions to call on.

autoload colors; colors

### Script-Local Constants
declare -r this_script_name="Mimis Actions Catalog"
declare -r this_script_version="1.0.0"
declare -r this_script_description="A catalog of available shell actions and functions in the Mimis actions framework."
declare -r relative_presentation_file_path="presentation"

## Common functions for the Mimis Actions Framework
declare -r commons_library='utilities/src/main/sh/lib/actions-library-commons.sh'

### Runtime Configuration
declare run_only_composite_functions=true                                                            # By default, only composite functions are executed.

declare -t _actions_commons_debug_last_directory=""
integer numeric_response=-1


### Expected Script-Global Variables
project_root_directory="$(git rev-parse --show-toplevel)"
declare -rx project_root_directory

# shellcheck source=../fluffle
source "$project_root_directory/$relative_presentation_file_path"
# shellcheck source=util/src/main/sh/lib
source "${project_root_directory}/$commons_library"
declare _actions_commons_debug_last_directory="${PWD}"                                              # Commons library writes to this variable, if present.
declare -Ag _actions_commons_debug_log=()                                                           # Commons library adds to this array, if present.


### Local Functions

## Capture parameters passed to the script, allowing for overrides.
#
# @param mode if set to "--debug", all functions will be run, not just the composite ones.
capture_parameters(){
  local -r mode=${1:-"none"}; [[ "$mode" == "--debug" ]] && run_only_composite_functions=false

  if [[ "$run_only_composite_functions" == true ]]; then
    print "=> Action Functions:"
  else
    print "=> All functions."
  fi
}

demo_actions(){
  print "=> Composite functions:"
}


main(){
  pushd "$project_root_directory" &> /dev/null || exit 11                                           # Always execute from the root of the repo.

  print_welcome_title "$this_script_name" "$this_script_version" "$this_script_description"
  capture_parameters "$@"

  demo_actions


  popd &> /dev/null || exit 13
}

main "$@"
