#!/usr/bin/env zsh

#===================================================================================================#
### Uniform presentation formatting constants                                                       #
# Author: rdd13r <12781006+rdd13r@users.noreply.github.com>                                         #
# Date: 2025-03-31                                                                                  #
# version: 1.0.0                                                                                    #
### --- Description ------------------------------------------------------------------------------- #
# This in an INCLUDE file for the scripts that  print to Agent console in uniformed way.            #
# It can be included in any of the repository scripts.                                              #
### ... Fields: ....................................................................................#
#===================================================================================================#
# shellcheck disable=SC2051,SC2059

### === Formatting Consistency ===
typeset -rx divider='|'
typeset -rx format_s_data_param="%s=%s\n"
typeset -rx format_i_data_param="%s=%'i\n"
typeset -rx format_f_data_param="%s=%'.2f\n"
typeset -rx format_f4_data_param="%s=%'.4f\n"

## === Separators ===
typeset -rix page_width=200 divider_length=3 margin_length=24 title_length=32 version_length=12 description_length=112                # Expected in production

## === Bars ===
bar_h1="$(printf -- '=%.0s' {1..${page_width}})"
bar_h2="$(printf -- '~%.0s' {1..${page_width}})"
bar_h3="$(printf -- '.%.0s' {1..${page_width}})"

## === Descriptor Titles ===
typeset -ri title_fill_margin=$(( page_width - margin_length - title_length - 4 - 2 ))                                                                                                                  # 2+2 spaces for bars, 1+1 spaces around field
typeset -ri title_version_fill_margin=$(( page_width - margin_length - title_length - version_length - 4 - 3 - 2 ))                                                                                     # 2+2 spaces for bars, 1+1+1 spaces around 2 fields, 2 spaces for '- '
typeset -ri title_version_description_fill_margin=$(( page_width - margin_length - title_length - version_length - description_length - 4 - 4 - 3 ))                                                    # 2+2 spaces for bars, 1+1+1+1 spaces around 4 fields, 3 spaces for '- ' and colon

typeset -rx fmt_bar_with_title="| %1\$-${margin_length}.${margin_length}s %2\$${title_length}.${title_length}s %1\$${title_fill_margin}.${title_fill_margin}s |\n"
typeset -rx fmt_bar_with_title_version="| %1\$-${margin_length}.${margin_length}s %2\$${title_length}.${title_length}s - %3\$-${version_length}.${version_length}s %1\$${title_version_fill_margin}.${title_version_fill_margin}s |\n"
typeset -rx fmt_bar_with_title_version_description="| %1\$-${margin_length}.${margin_length}s %2\$${title_length}.${title_length}s - %3\$-${version_length}.${version_length}s: %4\$-${description_length}.${description_length}s %1\$${title_version_description_fill_margin}.${title_version_description_fill_margin}s |\n"



typeset -rx bar_h1 bar_h2 bar_h3


### === Presentation Functions ===

print_welcome_title() {
  local -r actionTitle="${1:-"no title"}"
  local -r actionVersion="${2:-" no version"}"
  local -r actionDescription="${3:-"no description"}"

  print "$bar_h1"
  printf "$fmt_bar_with_title_version_description" "$bar_h2" "$actionTitle" "v$actionVersion" "$actionDescription"
  printf "$fmt_bar_with_title_version_description" "$bar_h3" "$(basename "$SHELL")" "$(uname)" "$(whoami)@$(hostname)"
  print "$bar_h2"
}


print "sourced -> presentation"
