#!/usr/bin/env zsh
# rdd13r 20241007

### IMPORTANT!!!
#./config.sh --url https://github.com/Gervi-Hera-Vitr --token ADBQLTRN3UQDLKGT4DPAZADJC5SZ2
readonly runner_labels='self-hosted,Linux,X64,dependency-submission,housekeeping,builder,codacy,qodana,jekyll'
readonly runner_name='goo'
runner_url='https://github.com/Gervi-Hera-Vitr'
runner_token='ADBQLTRN3UQDLKGT4DPAZADJC5SZ2'

app_archive='/home/actions-runner-linux-x64-2.329.0.tar.gz'

# shellcheck disable=SC2015
if [ ! -f "$app_archive" ]; then
  printf "ERROR:==>\t\t\tApplication archive is missing. (%s)\nEXITING....\n\n" "$app_archive"
  exit
else
  printf "(Using %s)\n" "$app_archive"
fi

for i in {1..3}; do
  agent_name="$runner_name-$i"
  agent_home="${HOME}/.agents/$agent_name"
  printf "\nSibling agent #%d (%s):" "$i" "$agent_name"
  if [ ! -d "$agent_home" ]; then
    printf "\tCreating home for (%s): %s\n" "$agent_name" "$agent_home"
    mkdir -p "$agent_home"
  else
    printf "\t%s exists...\n" "$agent_home"
  fi

  pushd "$agent_home" &> /dev/null || {
    printf "ERROR:==>\t\t\tAgent home directory for %s (%s) does NOT exist!\n\n" "$agent_name" "$agent_home"
    continue
  }

  if [ ! -f "./run.sh" ]; then
    printf "INSTALL==>\t\t\t%s\n" "$agent_name"
    tar xzf "$app_archive"
  else
    printf "NOOP-->\t\t\t%s is already installed" "$agent_name"
  fi

  ./config.sh \
    --unattended \
    --replace true \
    --url "$runner_url" \
    --token "$runner_token" \
    --name "$agent_name" \
    --labels "$runner_labels"

  popd &> /dev/null || continue
done


##### Config Instructions:
#
# Commands:
#  ./config.sh         Configures the runner
#  ./config.sh remove  Unconfigures the runner
#  ./run.sh            Runs the runner interactively. Does not require any options.
#
# Options:
#  --help     Prints the help for each command
#  --version  Prints the runner version
#  --commit   Prints the runner commit
#  --check    Check the runner's network connectivity with GitHub server
#
# Config Options:
#  --unattended           Disable interactive prompts for missing arguments. Defaults will be used for missing options
#  --url string           Repository to add the runner to. Required if unattended
#  --token string         Registration token. Required if unattended
#  --name string          Name of the runner to configure (default captain-ws)
#  --runnergroup string   Name of the runner group to add this runner to (defaults to the default runner group)
#  --labels string        Custom labels that will be added to the runner. This option is mandatory if --no-default-labels is used.
#  --no-default-labels    Disables adding the default labels: 'self-hosted,Linux,X64'
#  --local                Removes the runner config files from your local machine. Used as an option to the remove command
#  --work string          Relative runner work directory (default _work)
#  --replace              Replace any existing runner with the same name (default false)
#  --pat                  GitHub personal access token with repo scope. Used for checking network connectivity when executing `./run.sh --check`
#  --disableupdate        Disable self-hosted runner automatic update to the latest released version`
#  --ephemeral            Configure the runner to only take one job and then let the service un-configure the runner after the job finishes (default false)
#
# Examples:
#  Check GitHub server network connectivity:
#   ./run.sh --check --url <url> --pat <pat>
#  Configure a runner non-interactively:
#   ./config.sh --unattended --url <url> --token <token>
#  Configure a runner non-interactively, replacing any existing runner with the same name:
#   ./config.sh --unattended --url <url> --token <token> --replace [--name <name>]
#  Configure a runner non-interactively with three extra labels:
#   ./config.sh --unattended --url <url> --token <token> --labels L1,L2,L3
#