#!/usr/bin/env zsh

typeset -r python_version='3.12'

#typeset -r zsh_custom_plugins="${HOME}/.oh-my-zsh/custom/plugins"
#typeset -r zsh_conda_plugin='conda-zsh-completion'
#typeset -r zsh_conda_plugin_url='https://github.com/conda-incubator/conda-zsh-completion'

#if [[ ! -d "$zsh_custom_plugins/$zsh_conda_plugin" ]]; then
#  pushd "$zsh_custom_plugins" || exit 7
#  git clone "$zsh_conda_plugin_url"
#  popd || exit 9
#  #shellcheck source=${HOME}/.zshrc
#  source ~/.zshrc
#fi


#print "First time (base) environment initialization."
#print "NOTE:       This will lock Python version to $python_version."
#print "NOTE:       This will trigger first update check."

conda install python=$python_version
conda update -n base -c conda-forge conda
conda update --all

conda info
mamba info

conda create -n ml python=$python_version numpy scipy pandas ipython matplotlib jupyter scikit-learn sympy nose black
conda info --envs
conda activate ml
