#!/usr/bin/env zsh
# rdd13r 20241007

tee <<EOF

======================================
 Initialize SDKMan              ==>
======================================

EOF

# idempotent to latest
# shellcheck source=${HOME}/.sdkman/bin/sdkman-init.sh
source "$SDKMAN_INIT"
sdk selfupdate
sdk update
sdk upgrade
sdk install java
sdk install java 21.0.9-tem
sdk install kotlin
sdk install kobweb
sdk install gradle
sdk install scala
sdk install sbt
sdk install maven
sdk install maven 3.9.11
sdk c
sdk flush --all


tee <<EOF


======================================
 Done with SDKMan                  ==|
======================================

EOF



tee <<EOF

======================================
|= Initialization is complete!     =|
======================================
| Please execute                     |
|    Agent configuration             |
|        NEXT!                       |
|====================================|

EOF