name: "Detect Ruby"
description: "Checks Ruby version matches expected exactly."
author: "rdd13r"
branding:
  icon: alert-circle
  color: "red"

inputs:
  ruby-version:
    description: "Expected Ruby version (exact match)"
    required: true

outputs:
  failed:
    description: "true if version does not match"
    value: ${{ steps.detect.outputs.failed }}

runs:
  using: "composite"

  steps:

    - id: detect
      shell: zsh -l {0}
      run: ${{ github.action_path }}/detect-ruby.sh ${{ inputs.ruby-version }}
