= GitHub Actions: Agent Bootstrap and Local Box
R!dd13r rdd13r <12781006+rdd13r@users.noreply.github.com>
v1.1.0, Saturday 25th November 2025
:description: Instructions and assets to bootstrap a stateful GitHub Actions agent for AI ML projects.
:sectnums:
:sectanchors:
:sectlinks:
:icons: font
:tip-caption: 💡️
:note-caption: ℹ️
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠️
:source-highlighter: rouge
:toc: preamble
:toclevels: 3
:toc-title: Stateful Agent
:keywords: AI ML GitHub Actions Agent Bootstrap
:imagesdir: ./src/docs/resources/images
ifdef::env-name[:relfilesuffix: .adoc]
:linux-install-gh: https://github.com/cli/cli/blob/trunk/docs/install_linux.md
:miniforge-home: https://github.com/conda-forge/miniforge
:conda-manage-envs: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
:conda-user-guide: https://docs.conda.io/projects/conda/en/latest/user-guide/index.html
:blog-state-of-ruby: https://dev.to/yet_anotherdev/state-of-ruby-what-version-manager-to-use-4gbg
:ruby-bible: https://www.ruby-lang.org/en/documentation/installation/
:ruby-quick: https://www.ruby-lang.org/en/documentation/quickstart/

These are short instructions on how Mímis Gildi builds and deploys GitHub Actions agent for schools including AI ML projects.
There are two parts to this runbook: *Self-Hosted Runners* and *Local Box*.

Self-Hosted Runners::
This is production.
The GitHub Actions Agent is installed on self-hosted runners.
The runners thus have access to the private Mimis Gildi infrastructure.
This includes access to ASE Inc. MATILDA AI Platform (_Tillie_).
To begin with, the runners can be stateful.
Eventually, the combination of stateful and stateless runners will be supported.
Importantly, *_the runners define the current production dependency versions_*.
____
The Production::
* Debian 12 `bookworm`;
** Any Debian 12 descendant;
** i.e., `Ubunty`, `Mint`
* Pyhon >= 3.12.8;
* Tensorflow >= 2.17.0; **
____

Local Box::
This is development.
Currently, Munchkins have the following workstation types in use:
- Linux (Debian 11 and 12) *_workstations_* with GPU CUDA capability;
* *Debian 12:* _as in **production**_;
* *Mint 22.1:* _as in **production**_;
* *Debian 11:* Python==3.11.11, Tensorflow==2.12.0, CUDA 9.0.176;
- MacBook Pro (Intel) *mobile _workstations_* with CPU Tensorflow plugin;
* Python==3.11.11, Tensorflow==2.13.1, `tensorflow-metal`==1.0.0;
- MacBook Pro (Mx) *mobile _workstations_* with GPU Tensorflow plugin;
* _As in **production**_;

The Tensorflow dependencies thus are geared towards the lowes denominator of Mac Intell support.
Tests are expected to run comparably on all workstation types and production environments used.

== Self-Hosted Runners

Reference: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners[About Self-Hosted Runners].

=== Base OS: Debian Stable

[NOTE]
.Linux administration is out of scope for this runbook:
====
The starting point is expected to be a well-configured Debian Stable (currently `bookworm`) OS as is established by the https://github.com/mimis-gildi[Mímis Gildi] governance organization.
====

==== Agent Hardware

[IMPORTANT]
.Minimum expectations for the *_agent_* host:
====
- AMD64 CPU;
- Multicore (increments of 4), 4-8-12-etc.;
- 4-8-16-32GB RAM;
- instance slicing on the above specifications.
====

==== `sysbench` benchmarking

See link:./src/main/sh/bench.sh[bench.sh] for details.

==== Package Manager: `apt` configuration:

Initial `apt` configuration:

[source,shell]
./etc/sources.list
----
deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware

deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware

# bookworm-updates, to get updates before a point release is made;
# see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
----

==== Core Packages:

For posterity, here is one example of the host OS baseline setup.

[source,shell]
.Host OS Baseline:
----
apt update && apt dist-upgrade -y \
&& apt install -y build-essential linux-source module-assistant \
apt-transport-https apt-file debian-goodies software-properties-common ca-certificates \
zsh zsh-autosuggestions zsh-doc zsh-syntax-highlighting zsh-theme-powerlevel9k \
jq psmisc curl wget gnupg2 unzip zip speedtest-cli mutt hardinfo htop nmap tree \
vim vim-addon-manager vim-scripts vim-syntastic \
git git-extras git-lfs git-doc git-extras git-man \
lm-sensors sysbench smartmontools \
&& apt autoremove -y \
&& apt autoclean -y \
&& rm -rf /var/lib/apt/lists/*
# Above - may say no if package list is still needed (not common).

m-a prepare && m-a update
# Above - check with m-a

----

=== User Account Templating

. Acquire `zskel` as zskel.tgz from Mímis Gildi;
.. `zsh` is the default shell;
.. `oh-my-zsh` is the default plugin manager;
.. `sdkman` is the default JVM SDK package manager;
... `jdk-temurin`, `kotlin`, `gradle` - all _latest_ (LTS) versions;
.. `mini-forge` (mini-conda) is the default Python package manager;
... default environment `ml` matching coterminous `colab`;
.. `volta` is the default Node.js package manager;
... `node` at latest LTS;
.. `asdf` is the default Ruby package manager;
... `ruby` at latest LTS;
.. `GitHub CLI` Agent deployed to `~/.actions` directory;
... `~/var/runner/` directory is the working directory for the GitHub Actions agent;
... `~/var/runner/` directory is symlinked to `/var/runner/{code-name}` directory;

[source,shell]
----
cd /etc
tar -xvvf zskel.tgz
----

=== `adduser` configuration

[source,shell]
./etc/adduser.conf
----
# /etc/adduser.conf: `adduser' configuration.
# See adduser(8) and adduser.conf(5) for full documentation.

# A commented out setting indicates that this is the default in the
# code. If you need to change those settings, remove the comment and
# make your intended change.

# The login shell to be used for all new users.
# Default: DSHELL=/bin/bash
DSHELL=/usr/bin/zsh

# The directory in which new home directories should  be  created.
# Default: DHOME=/home
# DHOME=/home

# The directory from which skeletal user configuration files
# will be copied.
# Default: SKEL=/etc/skel
SKEL=/etc/zskel

# ...
----

=== Create GitHub Actions Agents _Shared Group_

[source,shell]
.Create a group for all agent users:
----
addgroup github
----

This will allow sharing /var content among the agents if required.

=== Create GitHub Actions Agent User

[source,shell]
.Agent user fo \{github-organization-slug\}:
----
#adduser --verbose --disabled-password github-your-organization-slug
----

[NOTE]
.Fields answered have lookup meanings.
====

Consider this example:

[source,shell]
.A Mímis Gildi agent user example:
----
#adduser --verbose --disabled-password github-mimis-gildi
# Adding user `github-mimis-gildi' ...
# Adding new group `github-mimis-gildi' (1003) ...
# Adding new user `github-mimis-gildi' (1003) with group `github-mimis-gildi (1003)' ...
# Creating home directory `/home/github-mimis-gildi' ...
# Copying files from `/etc/zskel' ...
# Changing the user information for github-mimis-gildi
# Enter the new value, or press ENTER for the default
#	Full Name []: Yoshi Mimis Gildi Runner
#	Room Number []: 102
#	Work Phone []: 2
#	Home Phone []: 2
#	Other []: 2
# Is the information correct? [Y/n]
# Adding new user `github-mimis-gildi' to supplemental / extra groups `users' ...
# Adding user `github-mimis-gildi' to group `users' ...
----
See Mímis Gildi documentation for naming conventions as well as index numbers meanings and their use.
====

[source,shell]
.Add user to sharing groups:
----
usermod -aG github,www-data github-your-organization-slug
----

=== Test GitHub Actions Agent User

[source,shell]
.Test GitHub Actions Agent User:
----
su - github-your-organization-slug
sdk selfupdate
----

=== Bind New Agent

Navigate to your organization's settings page and add the new agent, choosing Linux.

 Settings => Actions => Runners => Add runner => "New runner"

[NOTE]
.Example of a new runner activation command:
====

`./config.sh --url https://github.com/Yer-Organization-Slug --token ADBQLTSHLILKAWGIG5FWERLHGBZ2U`

====

[source,shell]
.Log into the new agent user, bind, and invoke the agent:
----
su - github-your-organization-slug
cd .actions
./config.sh --url https://github.com/Yer-Organization-Slug --token YerOrganizationNewToken
./run.sh
----

[NOTE]
.Example of a new runner activation success:
====

Possible agent console output:

[source,shell]
----
➜  .actions ./run.sh

√ Connected to GitHub

Current runner version: '2.320.0'
2024-11-10 07:55:04Z: Listening for Jobs
----

Break with Ctl-C key combination

[IMPORTANT]
.Agen configuration conventions example"
======

- Name: HostName for OrganizationName
- +Label: hostname
- Working directory: `$HOME/var/runner`

 where `runner` is a symlink to fast managed storage.

.Live example from Toad:
[%nowrap,shell]
....
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration

Enter the name of the runner group to add this runner to: [press Enter for Hera-Virt]

Enter the name of runner: [press Enter for toad] Toad for Gervi Héra Vitr

This runner will have the following labels: 'self-hosted', 'Linux', 'X64'
Enter any additional labels (ex. label-1,label-2): [press Enter to skip] toad

√ Runner successfully added
√ Runner connection is good

# Runner settings

Enter name of work folder: [press Enter for _work] /home/github-gervi-hera-virt/var/runner

√ Settings Saved.

➜  /home/github-gervi-hera-virt/var/runner -> /srv/var/actions/github-gervi-hera-virt

....

======

====

== Install Docker for Actions to use

[source,shell]
.Docker installation:
----
sudo su -
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
cat  /etc/apt/sources.list.d/docker.list

apt update && apt -y dist-upgrade
apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
----

Example of the resulting Apt repository list for Docker:

[source,shell]
./etc/apt/sources.list.d/docker.list
----
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
----

[source,shell]
.Add agents to the `docker` group:
----
sudo su -
groupadd docker
usermod -aG docker github-your-organization-slug
----

[TIP]
.Checking your user:
====
`lslogins github-your-organization-slug`
====

[NOTE]
.Example of the resulting `lslogins` output for established agent:
====
Redacted output:

[source,shell]
.on Mimis Gildi agent:
----
➜  lslogins github-mimis-gildi
Username:                           github-mimis-gildi
UID:                                1003
Gecos field:                        Yoshi Mimis Gildi Runner,102,2,2,2
Home directory:                     /home/github-mimis-gildi
Shell:                              /usr/bin/zsh
No login:                           no
Password is locked:                 yes
Password not required (empty):      yes
Login by password disabled:         no
Primary group:                      github-mimis-gildi
GID:                                1003
Supplementary groups:               docker,www-data,users,github
Supplementary group IDs:            996,33,100,1001
Last terminal:
Last hostname:
Hushed:                             no
Password expiration warn interval:  7
Password changed:                   Nov09/19:00
Maximum change time:                99999
Running processes:                  0

Last logs:
----
====


[source,shell]
.Test Docker:
----
su - github-your-organization-slug
docker run --rm hello-world; docker ps
----


[WARNING]
.Consider adequate testing!
====
It is customary to log into the Agent user account and invoke the `run.sh` script to test the agent through some *_real workflow executions_*.
====

== Make Agent _Permanent_

If everything is A-OK, let's add a sysctl service for our agent.

=== Create Service Configuration

[source,shell]
./etc/systemd/system/github-yer-organization-slug.service
----
[Unit]
Description=YerHost YerOrg GitHub Actions Runner
After=network.target

[Service]
User=github-yer-organization-slug
WorkingDirectory=/home/yer-organization-slug/.actions
ExecStart=/home/yer-organization-slug/.actions/run.sh
Restart=always

[Install]
WantedBy=multi-user.target

----

Then:

. `systemctl daemon-reload`
. `systemctl enable github-yer-organization-slug`
. `systemctl start github-yer-organization-slug`
. `systemctl status github-yer-organization-slug`
. `journalctl -u github-yer-organization-slug -f`

== Enhance Agent Abilities

There are additional tools, although usually strictly necessary,
yet quiet frequently used in Mímis Gildi workflows.

This section goes over some of them: the ones that are most likely to be used by the Gervi Hera Virt team.

=== GitHub CLI: Workflow Management Jobs

[IMPORTANT]
.GitHub CLI from Debian is *_outdated_*!
====
Though it is possible to install `gh` from the Distribution APT repository, we do NOT recommend it.
====

[source,shell]
.*_Latest_* => {linux-install-gh}[GitHub CLI installation] <=
----
(type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y
----

[WARNING]
.Do NOT authenticate CLI via `gh auth login`!
====
While it is okay to `login` as the `actions` user to test the CLI +
(and there is a dedicated token for this purpose `@lugaru`) +
please, DO NOT authenticate via `gh auth login` +
as the `actions` user! +
If you already have, then log out: `gh auth logout`. +
_Having an agent logged in is a security hole!_ +
{nbsp} +
Workflow will provide its own token fine-tuned to workflow needs; +
_so let that be._
====

[source,shell]
.Configure for each agent user:
----
gh config set git_protocol ssh
----

=== Add local SDKs

[source,shell]
.Add `gradle`, `kotlin`, and `java` SDKs:
----
sdk install gradle
sdk install kotlin
sdk install java
----

[source,shell]
.Check SDK:
----
sdk current
----

=== Add Ruby SDKs for Jekyll

Save this script to `/home/lugaru/bin/ruby-up.sh`, make it executable, and run it:

[source,shell]
.Add `ruby` SDKs:
----
include::src/main/sh/ruby-up.sh[]
----

There are *_many_* tools designed to manage Ruby versions. +
From trivial to comprehensive.
For example, Mímis Gildi +
use `asdf` with a Ruby plugin for the local box.
And then +
`rbenv`, `chruby`, `rvm`, `rbenv-bundler`, `rbenv-gemset` +
etc. - a ton of tools.
But most, if not all, call _this_ program: +
https://github.com/rbenv/ruby-build[*_ruby-build_*], packaged as a gem. See {ruby-bible}[the Ruby bible here].

Hence, we use `ruby-build` directly in the ruby-up script.

Albeit [.small]#not# *_too_* [.small]#_shiny_# new, Ruby is a {ruby-quick}[_good language to learn_].


=== Add dedicated `conda` for ML: {miniforge-home}[conda-forge/miniforge]

[NOTE]
.This also sets up the default `ml` environment for GitHub AI Actions.
====
Any conda environment is fine for the projects except `base`, +
which is 1) set up as the default; and, 2) reserved for `conda`; +
thus *_should not be polluted_*! +
{nbsp} +

Luckily, old Mímis Gildi hackers publish a few standard environments +
that are suitable for GitHub Actions AI projects.
The general one is `ml`. +
And that is the one we will provision automatically.
====


[source,shell]
.Add `conda` for ML:
----
include::src/main/sh/conda-up.sh[]
----

By the agent convention this script is located in the ~/bin directory and named `conda-up`. +
Listing this directory, one will find another script there already:

.Example of bin before the `conda-up` script creation:
....
➜  bin l
total 12K
drwxr-xr-x  2 github-gervi-hera-vitr github-gervi-hera-vitr 4.0K Nov  9 23:38 .
drwx------ 16 github-gervi-hera-vitr github-gervi-hera-vitr 4.0K Nov 17 04:15 ..
-rwx------  1 github-gervi-hera-vitr github-gervi-hera-vitr  851 Nov  9 23:38 init-actions
➜  bin
....

.Example of bin after the `conda-up` script creation:
....
➜  bin l
total 16K
drwxr-xr-x  2 github-gervi-hera-vitr github-gervi-hera-vitr 4.0K Nov 17 04:16 .
drwx------ 16 github-gervi-hera-vitr github-gervi-hera-vitr 4.0K Nov 17 04:16 ..
-rwxr-xr-x  1 github-gervi-hera-vitr github-gervi-hera-vitr  544 Nov 17 04:16 conda-up
-rwx------  1 github-gervi-hera-vitr github-gervi-hera-vitr  851 Nov  9 23:38 init-actions
➜  bin
....

Run the `conda-up` script::

Execution will complete with the `~/.zshrc` modified - examine the modifications.

Logout and back in again to see the changes::

This action will cause conda block within `~/.zshrc` to activate your environment:

.Base environment is activated, your prompt will look like this:
....
(base) ➜  ~
....

[WARNING]
.Missed `conda` shell activation?
====

[source,shell]
.then bootstrap for `zsh` manually:
----
conda init zsh
----
====

[TIP]
.Direct `conda` environment activation examples:
====

[source,shell]
.use `mamba`:
----
micromamba activate /home/github-gervi-hera-vitr/miniforge3
# or
micromamba activate /home/github-gervi-hera-vitr/miniforge3/envs/ml
----
====

[TIP]
.To run a single job:
====
[source,shell]
----
micromamba run -p /home/github-gervi-hera-vitr/miniforge3/envs/ml oddJob
----
====

=== Setting up `ml`, and {conda-manage-envs}[_managing environments_]:

[IMPORTANT]
.Strict Python ecosystem *version locking is a SAD Necessity*!
====
. Build fidelity depends on tested correlation of library versions;
. `tensorflow` -- primary dependency introducing the `ml` environment;
. `python` -- secondary dependency limited by both `tensorflow` and the *runtime*;
. `CUDA` -- final dependency limited by hardware support on `prod`, `trunk` and `dev`;
. `python=3.12.8` -- the current highest version supported by Linux and OSX #Tillie kernel extensions#!

_By deviating from these production tested versions, we risk having inoperable local._ +
Also, please remember that: +
1) `python=3.12.x` is a 'fuzzy' matching, while; +
2) `python==3.12.x` is a 'strict' matching; +
3) `mamba` keeps a pinned file in the environment configuration directory; +
4) Only the 'major' version of `python` should be component locked, i.e., `python=3.12`.
====

[source,shell]
.Baseline BASE environment:
----
conda install python==3.12.8
conda update -n base -c conda-forge conda
conda update --all
----

[CAUTION]
.The last `conda update --all` command should have bumped `mamba`.
====
_Your forge may have been shipped with generation 1 mamba like so:_

 mamba                     1.5.12          py312h9460a1c_0    conda-forge

_And should have been upgraded to generation 2 like so._

 mamba                     2.0.5                h8871ed4_1    conda-forge

If that hasn't occurred for whatever reason, fix by running:

.Mamba command `upgrade` only exists in the first generation of mamba.
----
[source,shell]
mamba upgrade mamba
----
====

[source,shell]
.Crate and activate an empty `ml` component environment:
----
conda create -n ml python==3.12 numpy scipy pandas ipython matplotlib jupyter scikit-learn sympy nose
conda info --envs
# Activate `ml` environment:
conda activate ml
----

_**If happy with the `ml` environment: make it the default**_: +
add the following to `~/.zshrc`: `conda activate ml`.

[CAUTION]
.The convention is -- per workflow!
====
Although having a reference environment is good, it is not recommended to pollute it with your own workflow dependencies.
The best practice is to have an ML build workflow manage its own environment during a pipeline execution.
====

See [.big]#{conda-user-guide}[Conda User Guide]# for more information.

== Summary

This is a summary runbook for a templated GitHub Actions agent setup within the Mímis Gildi organizations ecosystem.

More to follow.

-Rdd13r