source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"

gem "rake"
gem "tzinfo-data", "~> 1.2024", ">= 1.2024.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17.0"
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jekyll-include-cache", "~> 0.2.1"
  gem "jekyll-data", "~> 1.1.1"
  gem "jekyll-asciidoc", "~> 3.0.0"
  gem "jekyll-paginate-v2", "~> 3.0"
  gem "jekyll-gist", "~> 1.5"
  gem "jekyll-algolia", "~> 1.7"
  gem "jekyll-archives", "~> 2.2"
  gem "jemoji", "~> 0.13.0"
  gem "csv", "~> 3.3.0"
  gem "base64", "~> 0.2.0"
end

# Local development
gem "webrick", "~> 1.8", ">= 1.8.2"
gem "jekyll-remote-theme", "~> 0.4.3"