name: Cache Prune
run-name: "Pruned Old Caches on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    types:
      - completed
    workflows:
      - "Actions Prune"
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-cache-prune"
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

defaults:
  run:
    shell: zsh -l {0}

jobs:

  prune-actions-cache:
    timeout-minutes: 7
    runs-on: self-hosted
    name: "Prune GitHub Actions Cache"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@v6.0.2
        timeout-minutes: 1


      - name: "Prune stale caches"
        uses: Mimis-Gildi/fluffle/.github/actions/prune-workflow-caches@main
        timeout-minutes: 5
